3d_tiles: False
auto_boundary: True
build_overviews: False
camera_lens: "auto"
cog: True
crop: 3
debug: False
dem_decimation: 1
dem_euclidean_map: False
dem_gapfill_steps: 3
dem_resolution: 5
depthmap_resolution: 640
dsm: False
dtm: False
end_with: odm_postprocess
fast_orthophoto: True
feature_quality: high
feature_type: sift
force_gps: False
gps_accuracy: 10
ignore_gsd: False
matcher_neighbors: 0
matcher_type: flann
max_concurrency: 32
merge: all
mesh_octree_depth: 11
mesh_size: 200000
min_num_features: 10000
no_gpu: False
optimize_disk_space: False
orthophoto_compression: DEFLATE
orthophoto_cutline: True
orthophoto_kmz: True
orthophoto_no_tiled: False
orthophoto_png: True
orthophoto_resolution: 4
pc_classify: False
pc_copc: False
pc_csv: False
pc_ept: True
pc_filter: 2.5
pc_geometric: False
pc_las: False
pc_quality: medium
pc_rectify: False
pc_sample: 0
pc_tile: False
primary_band: auto
radiometric_calibration: none
rolling_shutter: False
sfm_algorithm:  triangulation
skip_3dmodel: True
skip_band_alignment: False
skip_orthophoto: False
skip_report: False
sky_removal: False
smrf_scalar: 1.25
smrf_slope: 0.15
smrf_threshold: 0.5
smrf_window: 18.0
split: 999999
texturing_data_term: gmi
texturing_keep_unseen_faces: False
texturing_outlier_removal_type: gauss_clamping
texturing_skip_global_seam_leveling: False
texturing_skip_local_seam_leveling: False
texturing_tone_mapping": none
tiles: True
time: True
use_3dmesh: False
use_exif: False
use_fixed_camera_params: False
use_hybrid_bundle_adjustment: False
verbose: False
